name: Update TV Box URLs

# 触发条件: 可以按您的需要调整
on:
  #schedule:
    # 每天 UTC 时间 00:00 运行
    #- cron:  '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install requests
    - name: Update TV Box URLs
      run: |
        python update.py
